# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1359/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1359/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/storage/Documents/GitHub/lego-figure-maker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/storage/Documents/GitHub/lego-figure-maker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1359/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1359/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/storage/Documents/GitHub/lego-figure-maker/CMakeFiles /home/storage/Documents/GitHub/lego-figure-maker//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/storage/Documents/GitHub/lego-figure-maker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lego_figure_maker

# Build rule for target.
lego_figure_maker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lego_figure_maker
.PHONY : lego_figure_maker

# fast build rule for target.
lego_figure_maker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/build
.PHONY : lego_figure_maker/fast

HttpServer/IntermediaryServer/Generics/Socket/Socket.o: HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.o
.PHONY : HttpServer/IntermediaryServer/Generics/Socket/Socket.o

# target to build an object file
HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.o
.PHONY : HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.o

HttpServer/IntermediaryServer/Generics/Socket/Socket.i: HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.i
.PHONY : HttpServer/IntermediaryServer/Generics/Socket/Socket.i

# target to preprocess a source file
HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.i
.PHONY : HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.i

HttpServer/IntermediaryServer/Generics/Socket/Socket.s: HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.s
.PHONY : HttpServer/IntermediaryServer/Generics/Socket/Socket.s

# target to generate assembly for a file
HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.s
.PHONY : HttpServer/IntermediaryServer/Generics/Socket/Socket.cpp.s

HttpServer/IntermediaryServer/main.o: HttpServer/IntermediaryServer/main.cpp.o
.PHONY : HttpServer/IntermediaryServer/main.o

# target to build an object file
HttpServer/IntermediaryServer/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/IntermediaryServer/main.cpp.o
.PHONY : HttpServer/IntermediaryServer/main.cpp.o

HttpServer/IntermediaryServer/main.i: HttpServer/IntermediaryServer/main.cpp.i
.PHONY : HttpServer/IntermediaryServer/main.i

# target to preprocess a source file
HttpServer/IntermediaryServer/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/IntermediaryServer/main.cpp.i
.PHONY : HttpServer/IntermediaryServer/main.cpp.i

HttpServer/IntermediaryServer/main.s: HttpServer/IntermediaryServer/main.cpp.s
.PHONY : HttpServer/IntermediaryServer/main.s

# target to generate assembly for a file
HttpServer/IntermediaryServer/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/IntermediaryServer/main.cpp.s
.PHONY : HttpServer/IntermediaryServer/main.cpp.s

HttpServer/PiecesServer/Generics/Socket/Socket.o: HttpServer/PiecesServer/Generics/Socket/Socket.cpp.o
.PHONY : HttpServer/PiecesServer/Generics/Socket/Socket.o

# target to build an object file
HttpServer/PiecesServer/Generics/Socket/Socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/PiecesServer/Generics/Socket/Socket.cpp.o
.PHONY : HttpServer/PiecesServer/Generics/Socket/Socket.cpp.o

HttpServer/PiecesServer/Generics/Socket/Socket.i: HttpServer/PiecesServer/Generics/Socket/Socket.cpp.i
.PHONY : HttpServer/PiecesServer/Generics/Socket/Socket.i

# target to preprocess a source file
HttpServer/PiecesServer/Generics/Socket/Socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/PiecesServer/Generics/Socket/Socket.cpp.i
.PHONY : HttpServer/PiecesServer/Generics/Socket/Socket.cpp.i

HttpServer/PiecesServer/Generics/Socket/Socket.s: HttpServer/PiecesServer/Generics/Socket/Socket.cpp.s
.PHONY : HttpServer/PiecesServer/Generics/Socket/Socket.s

# target to generate assembly for a file
HttpServer/PiecesServer/Generics/Socket/Socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/PiecesServer/Generics/Socket/Socket.cpp.s
.PHONY : HttpServer/PiecesServer/Generics/Socket/Socket.cpp.s

HttpServer/PiecesServer/main.o: HttpServer/PiecesServer/main.cpp.o
.PHONY : HttpServer/PiecesServer/main.o

# target to build an object file
HttpServer/PiecesServer/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/PiecesServer/main.cpp.o
.PHONY : HttpServer/PiecesServer/main.cpp.o

HttpServer/PiecesServer/main.i: HttpServer/PiecesServer/main.cpp.i
.PHONY : HttpServer/PiecesServer/main.i

# target to preprocess a source file
HttpServer/PiecesServer/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/PiecesServer/main.cpp.i
.PHONY : HttpServer/PiecesServer/main.cpp.i

HttpServer/PiecesServer/main.s: HttpServer/PiecesServer/main.cpp.s
.PHONY : HttpServer/PiecesServer/main.s

# target to generate assembly for a file
HttpServer/PiecesServer/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lego_figure_maker.dir/build.make CMakeFiles/lego_figure_maker.dir/HttpServer/PiecesServer/main.cpp.s
.PHONY : HttpServer/PiecesServer/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lego_figure_maker"
	@echo "... HttpServer/IntermediaryServer/Generics/Socket/Socket.o"
	@echo "... HttpServer/IntermediaryServer/Generics/Socket/Socket.i"
	@echo "... HttpServer/IntermediaryServer/Generics/Socket/Socket.s"
	@echo "... HttpServer/IntermediaryServer/main.o"
	@echo "... HttpServer/IntermediaryServer/main.i"
	@echo "... HttpServer/IntermediaryServer/main.s"
	@echo "... HttpServer/PiecesServer/Generics/Socket/Socket.o"
	@echo "... HttpServer/PiecesServer/Generics/Socket/Socket.i"
	@echo "... HttpServer/PiecesServer/Generics/Socket/Socket.s"
	@echo "... HttpServer/PiecesServer/main.o"
	@echo "... HttpServer/PiecesServer/main.i"
	@echo "... HttpServer/PiecesServer/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

